[package]
name = "palindromos_primos_pi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is_prime = "2.0.9"
ureq = "2.5.0"
